version: "3.7"

services:
    elasticsearch:
        image: elasticsearch:7.17.5
        ## All of the ES settings can be set via the environment
        ## vars.
        environment:
            - discovery.zen.ping.unicast.hosts=["127.0.0.1"]
            - discovery.zen.minimum_master_nodes=1
        ## These exposed ports are for debugging only. .NET +
        ## Docker + MacOS == bad scene. (.NET always wants to
        ## use the hosts name, and on a mac that is actually
        ## a virtual machine, and not on the same network.)
        ports:
            - "9200:9200"
        networks:
            bestbetsloader:
                aliases:
                    - elasticsearch


networks:
    bestbetsloader:
